In [2]:
import pandas as pd 
import numpy as np
import re

In [3]:
# read data from excel
df = pd.read_excel('data_2.xlsx', skiprows=6)

# print the first 5 rows
df.head()

,Deal ID,Company ID,Company Name,Description,Investor ID,Investor Name,Investor Website,Investor Status,Primary Investor Type,Other Investor Types,...,Valuation/Cash Flow,Deal Status,Primary Industry Sector,Primary Industry Group,Primary Industry Code,Verticals,All Industries,Business Status,Financing Status,PitchBook Link
0,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,10768-06,BlackRock,www.blackrock.com,Active Investor,Asset Manager,"Fund of Funds, Hedge Fund, Impact Investing, I...",...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
1,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,58004-02,Bpifrance,www.bpifrance.fr,Active Investor,Sovereign Wealth Fund,"Accelerator/Incubator, Fund of Funds, Growth/E...",...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
2,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,187980-13,Cathay Innovation,www.cathayinnovation.com,Active Investor,Venture Capital,NaN,...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
3,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,523414-99,Delphi Ventures,delphiventures.io,Active Investor,Venture Capital,NaN,...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
4,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,11180-08,Eurazeo,www.eurazeo.com,Active Investor,PE/Buyout,"Growth/Expansion, Infrastructure, Venture Capital",...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26986 entries, 0 to 26985
Data columns (total 62 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Deal ID                                     26984 non-null  object
 1   Company ID                                  26983 non-null  object
 2   Company Name                                26983 non-null  object
 3   Description                                 26982 non-null  object
 4   Investor ID                                 26983 non-null  object
 5   Investor Name                               26983 non-null  object
 6   Investor Website                            22323 non-null  object
 7   Investor Status                             26983 non-null  object
 8   Primary Investor Type                       26983 non-null  object
 9   Other Investor Types                        14384 non-null  object
 10  Preferred Industries                        23960 non-null  object
 11  Preferred Verticals                         22411 non-null  object
 12  Investor HQ                                 25225 non-null  object
 13  Investor AUM (million, USD)                 12329 non-null  float64
 14  Lead Partner                                8147 non-null   object
 15  Lead Partner Email                          4393 non-null   object
 16  Lead Partner Phone                          3989 non-null   object
 17  Lead/Sole                                   26983 non-null  object
 18  Fund(s) Used                                5938 non-null   object
 19  Deal No.                                    26983 non-null  float64
 20  Deal Date                                   26983 non-null  datetime64[ns]
 21  Total Deal Size (million, USD)              24657 non-null  float64
 22  Deal Size Status                            24657 non-null  object
 23  Investment Size (million, USD)              5721 non-null   float64
 24  Deal Type 1                                 26983 non-null  object
 25  Deal Type 2                                 9188 non-null   object
 26  Deal Type 3                                 15 non-null     object
 27  Deal Class                                  26983 non-null  object
 28  Debts                                       5676 non-null   object
 29  Company City                                26799 non-null  object
 30  Company State/Province                      67 non-null     object
 31  Company Post Code                           26664 non-null  object
 32  Company Country/Territory                   26983 non-null  object
 33  Company Pre-money Valuation (million, USD)  16518 non-null  float64
 34  Company Post Valuation (million, USD)       16559 non-null  float64
 35  Company Post Valuation Status               16559 non-null  object
 36  Revenue (million, USD)                      6563 non-null   float64
 37  Revenue Status                              6485 non-null   object
 38  Revenue Growth since last deal              2958 non-null   float64
 39  Gross Profit (million, USD)                 943 non-null    float64
 40  Gross Profit Status                         943 non-null    object
 41  Net Income (million, USD)                   4896 non-null   float64
 42  Net Income Status                           4895 non-null   object
 43  EBITDA (million, USD)                       3971 non-null   float64
 44  EBITDA Status                               3971 non-null   object
 45  Debt/Equity                                 1824 non-null   float64
 46  Debt/EBITDA                                 818 non-null    float64
 47  Deal Size/EBITDA                            3631 non-null   float64
 48  Valuation/EBITDA                            2287 non-null   float64
 49  Deal Size/Revenue                           5992 non-null   float64
 50  Valuation/Revenue                           3901 non-null   float64
 51  Deal Size/Cash Flow                         286 non-null    float64
 52  Valuation/Cash Flow                         137 non-null    float64
 53  Deal Status                                 26983 non-null  object
 54  Primary Industry Sector                     26978 non-null  object
 55  Primary Industry Group                      26978 non-null  object
 56  Primary Industry Code                       26978 non-null  object
 57  Verticals                                   25035 non-null  object
 58  All Industries                              26978 non-null  object
 59  Business Status                             26983 non-null  object
 60  Financing Status                            26973 non-null  object
 61  PitchBook Link                              0 non-null      float64
dtypes: datetime64[ns](1), float64(20), object(41)
memory usage: 12.8+ MB

In [ ]:
# # Build the regex dynamically
# ignore_pattern = '|'.join(['Private\s+Equity', 'Financial\s+Services', 'Electrical\s+Equipment'])
# pattern = rf'\((?:[A-Z]{2,4}:\s*[A-Z0-9.]+)\)|\((?![A-Z]{2,4}:\s*[A-Z0-9.]+)(?!{ignore_pattern})([A-Za-zÀ-ÖØ-öø-ÿ-]+(?:\s+[A-Za-zÀ-ÖØ-öø-ÿ-]+)+)\)'

# # Compile regex for better performance
# compiled_regex = re.compile(pattern)

In [ ]:
# # Select the columns investors
# investors = df['Investors']

# # Function to extract partner names
# def extract_partners(text):
#     matches = re.findall(pattern, text)
#     # Flatten the list and remove empty strings
#     cleaned_matches = [match for sublist in matches for match in sublist if match]
#     return ", ".join(cleaned_matches) if cleaned_matches else None
    

# # Apply function to create 'partners' column only to the first 5 rows
# df["Partners"] = investors.apply(extract_partners)

In [8]:
from collections import Counter

# Function to filter two-word names
def get_two_word_names(partners_list):
    two_word_names = []
    for names in partners_list:
        if names:  # Ensure it's not None
            for name in names.split(", "):  # Handle multiple names
                if len(name.split()) == 2:  # Check if it has exactly two words
                    two_word_names.append(name)
    return two_word_names

# Extract all partner names from the column
all_partners = df["Lead Partner"].dropna().tolist()

# Get only two-word names
two_word_names = get_two_word_names(all_partners)

# Count occurrences
name_counts = Counter(two_word_names)

# Convert to DataFrame for visualization
df_name_counts = pd.DataFrame(name_counts.items(), columns=["Two-Word Name", "Frequency"]).sort_values(by="Frequency", ascending=False)

# Display the frequency table
df_name_counts.head(50)

                Two-Word Name  Frequency
437               Xavier Niel         99
256           Thibaud Elziere         41
2220          Guillaume Aubin         41
920           Joséphine Marie         33
846    Jean-David Chamboredon         28
56         Philippe Collombel         25
1432            Chahra Louafi         24
1223           Romain Lavault         24
793         Rodolphe Menegaux         24
2297           Marc Simoncini         22
2077  Jacques-Antoine Granjon         22
3060          Jérémie Berrebi         21
300                Celia Hart         20
63             Thierry Laugel         20
815          Vincent Deltrieu         19
1138       Benjamin Wainstain         19
466        Stéphanie Hospital         19
372              Claire Houry         18
87              Jérôme Guéret         18
1362              Valéry Huot         18
2296          Dominique Vidal         18
262           Renaud Guillerm         18
1765           Nicolas Boulay         18
761          Guillaume Meulle         18
518           Jean-Marc Bally         17
1873    Jean-Marc Patouillaud         17
772            Cyril Bertrand         17
1152         François Meteyer         16
51        Clémentine Cazenave         16
909            Bruno Guicheux         16
2116       Guillaume Hemmerle         16
739    Charles-Antoine Morand         16
317         Antoine Papiernik         15
319        Samantha Jérusalmy         15
1565          Olivier Mathiot         15
1354          Catherine Boule         15
1562         Guillaume Dupont         15
339            Antoine Freysz         15
701            Xavier Lazarus         15
1607         Oleg Tscheltzoff         15
420           Cyril Vermeulen         15
890            Thibaut Roulon         15
1260       Yann-Hervé Rusquec         15
789           Stéphane Pesqué         14
645           Reza Malekzadeh         14
464          Xavier Lorphelin         14
171             Alison Imbert         14
910         Charles Beigbeder         14
917       Bertrand Distinguin         14
1154             Raffi Kamber         14

In [5]:
# Drop rows where 'partners' column is NaN
df = df.dropna(subset=['Lead Partner'])

# Verify the result
df.head()

,Deal ID,Company ID,Company Name,Description,Investor ID,Investor Name,Investor Website,Investor Status,Primary Investor Type,Other Investor Types,...,Valuation/Cash Flow,Deal Status,Primary Industry Sector,Primary Industry Group,Primary Industry Code,Verticals,All Industries,Business Status,Financing Status,PitchBook Link
2,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,187980-13,Cathay Innovation,www.cathayinnovation.com,Active Investor,Venture Capital,NaN,...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
4,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,11180-08,Eurazeo,www.eurazeo.com,Active Investor,PE/Buyout,"Growth/Expansion, Infrastructure, Venture Capital",...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
5,249733-63T,464342-95,Flowdesk,Developer of a compliant trading and liquidity...,51189-94,HV Capital,www.hvcapital.com,Active Investor,Venture Capital,Growth/Expansion,...,NaN,Completed,Information Technology,Software,Financial Software,"Cryptocurrency/Blockchain, FinTech",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
30,272893-60T,530537-68,Wavo (Financial Software),Developer of a financial platform designed to ...,434507-50,Tony Parker,NaN,Active Investor,Angel (individual),NaN,...,NaN,Completed,Information Technology,Software,Financial Software,"Artificial Intelligence & Machine Learning, Fi...",Financial Software*; Other Financial Services,Generating Revenue,Venture Capital-Backed,NaN
32,285052-87T,512410-51,Smile Wanted Group,Operator of a digital advertising marketplace ...,58004-02,Bpifrance,www.bpifrance.fr,Active Investor,Sovereign Wealth Fund,"Accelerator/Incubator, Fund of Funds, Growth/E...",...,NaN,Completed,Business Products and Services (B2B),Commercial Services,Media and Information Services (B2B),"AdTech, Marketing Tech",Media and Information Services (B2B)*; Other C...,Generating Revenue,Venture Capital-Backed,NaN

In [6]:
# Save the results to a new csv file
df.to_csv('data.csv', index=False)